import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";


const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} justify-center flex h-[100vh] w-[100vw] antialiased bg-gradient-to-br from-[#f9fafb] to-[#d2d6db]`}
      >
        {children}
      </body>
    </html>
  );
}
